name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fce80b8e4d46728fe0e4fccab29caebde62a65d3b0c3ec4dcbf03c21ce18b58"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
