name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb4dd24d57f69088261d77a84dd8a48f453c15e79ae837beb2663ab5194c075a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
