name = "Cobblefriends"
author = "OlsyzZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70ed54ea2dcd2e4142e8dd228b268e0732bae97756ea8e9929b33f7aaeafd2e6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
